### ISSUE TITLE
Version 2.1.2 published without the dist directory

### ISSUE THREAD

**Issue by montgomery1944** [TheIdentitySelector/thiss-ds-js#56]
When trying to fetch https://unpkg.com/@theidentityselector/thiss-ds@2.1.2/dist/thiss-ds.js I am getting "Cannot find "/dist/thiss-ds.js" in @theidentityselector/thiss-ds@2.1.2", fetching https://unpkg.com/@theidentityselector/thiss-ds@2.1.1/dist/thiss-ds.js works properly.

After small investigation it seems, that version 2.1.2 was published without the dist directory.

Is it possible to fix it? Thanks.

**Comment by enriquepablo** [comment]
Oops sorry...

**Comment by enriquepablo** [comment]
There is now version 2.1.3 with dist/ restored
